ovabo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from app.views import ListProductView, CreateProductView, UpdateProductView, ListLineView, UpdateLineView, \
    CreateLineView, ListCalendarView, UpdateCalendarView, CreateCalendarView, CreateAgeGroupView, UpdateAgeGroupView, ListAgeGroupView, \
    CloneLineView, CloneAgeGroupView, CloneCalendarView, CloneProductView, CreateSellerView, UpdateSellerView, \
    ListSellerView
from data.views import LineSearchView, AdvancedLineSearchView, MissingPriceDataReport, MissingPriceDataLinesView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^(/)?$', TemplateView.as_view(template_name="app/welcome.html")),

    url(r'^products/add', CreateProductView.as_view(), name="product_add"),
    url(r'^products/(?P<pk>\w+)/edit(/)?', UpdateProductView.as_view(), name="product_edit"),
    url(r'^products/(?P<pk>\w+)/clone(/)?', CloneProductView.as_view(), name="product_clone"),
    url(r'^products(/)?', ListProductView.as_view(), name="product_list"),

    url(r'^lines/add', CreateLineView.as_view(), name="line_add"),
    url(r'^lines/(?P<pk>\w+)/edit(/)?', UpdateLineView.as_view(), name="line_edit"),
    url(r'^lines/(?P<pk>\w+)/clone(/)?', CloneLineView.as_view(), name="line_clone"),
    url(r'^lines(/)?', ListLineView.as_view(), name="line_list"),

    url(r'^calendar/add', CreateCalendarView.as_view(), name="calendar_add"),
    url(r'^calander/(?P<pk>\w+)/edit(/)?', UpdateCalendarView.as_view(), name="calendar_edit"),
    url(r'^calander/(?P<pk>\w+)/clone(/)?', CloneCalendarView.as_view(), name="calendar_clone"),
    url(r'^calendar(/)?', ListCalendarView.as_view(), name="calendar_list"),

    url(r'^age/add', CreateAgeGroupView.as_view(), name="agegroup_add"),
    url(r'^age/(?P<pk>\w+)/edit(/)?', UpdateAgeGroupView.as_view(), name="agegroup_edit"),
    url(r'^age/(?P<pk>\w+)/clone(/)?', CloneAgeGroupView.as_view(), name="agegroup_clone"),
    url(r'^age(/)?', ListAgeGroupView.as_view(), name="agegroup_list"),

    url(r'^seller/add', CreateSellerView.as_view(), name="seller_add"),
    url(r'^seller/(?P<pk>\w+)/edit(/)?', UpdateSellerView.as_view(), name="seller_edit"),
    url(r'^seller(/)?', ListSellerView.as_view(), name="seller_list"),

    url(r'^data/reports/missing_prices(/)?', MissingPriceDataReport.as_view(), name="data_report_missing-price"),
    url(r'^data/lines/missing_prices.json', MissingPriceDataLinesView.as_view(), name="data_lines_missing-price_json"),

    url(r'^data/lines/advanced(/)?', AdvancedLineSearchView.as_view(), name="data_search_adv_line"),
    url(r'^data/lines(/)?', LineSearchView.as_view(), name="data_search_line"),


]

admin.site.site_header = 'OVabo'

data/models.py
from __future__ import unicode_literals

from django.db import models

from django.utils.translation import ugettext_lazy as _
from django_enumfield import enum

from utils.enums import TransportMode, DATAOWNERCODE


class Line(models.Model):
    dataownercode = models.CharField(max_length=6, choices=DATAOWNERCODE)
    lineplanningnumber = models.CharField(max_length=25)
    publiclinenumber = models.CharField(max_length=25)
    headsign = models.CharField(max_length=100)
    transportmode = enum.EnumField(TransportMode)
    json_lines = models.TextField()

    ppt_id = models.CharField(max_length=20, blank=True, null=True)
    ppt_name = models.CharField(max_length=100, blank=True, null=True)

    entrance = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Opstaptarief", blank=True, null=True)
    rounding = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Afrondniveau", blank=True, null=True)
    maximum = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Maximum eenheden", blank=True, null=True)
    average_km_rate = models.DecimalField(max_digits=8, decimal_places=5, verbose_name="Gemiddeld tarief", blank=True, null=True)

    class Meta:
        verbose_name = _("Lijn")
        verbose_name_plural = _("Lijninformatie")
        unique_together = ('dataownercode', 'lineplanningnumber')

    def __unicode__(self):
        return "%s - %s" % (self.dataownercode, self.headsign)

data/views.py
import json

from operator import __or__ as OR
from operator import __and__ as AND
from django.db.models import QuerySet, Q
from django.views.generic import ListView

from data.models import Line
from django.core.cache import cache

from utils.views import JSONListResponseMixin


class MissingPriceDataReport(ListView):
    model = Line
    ordering = ['dataownercode', 'lineplanningnumber']

    def get_queryset(self):
        qry = super(MissingPriceDataReport, self).get_queryset()
        return qry.filter(ppt_id__isnull=True)

    def get_context_data(self, **kwargs):
        ctx = super(MissingPriceDataReport, self).get_context_data(**kwargs)
        ctx['total'] = self.model.objects.all().count()
        return ctx


class MissingPriceDataLinesView(JSONListResponseMixin, ListView):
    model = Line
    render_object = 'object_list'

    def get_queryset(self):
        qry = super(MissingPriceDataLinesView, self).get_queryset()
        qry = qry.filter(ppt_id__isnull=True).exclude(transportmode=1)
        line_list = qry.values('pk', 'dataownercode', 'headsign', 'lineplanningnumber', 'publiclinenumber', 'json_lines')
        for r in line_list:
            r['json_lines'] = json.loads(r['json_lines'])
        return line_list


class LineSearchView(JSONListResponseMixin, ListView):
    model = Line
    render_object = 'object_list'

    def get_queryset(self):
        qry = super(LineSearchView, self).get_queryset()
        needle = unicode(self.request.GET.get('search', ''))
        dataowner = self.request.GET.get('dataownercode', None)
        qry = qry.filter(Q(headsign__icontains=needle) | Q(publiclinenumber__startswith=needle) | Q(lineplanningnumber__startswith=needle) )\
            .order_by('lineplanningnumber')
        if dataowner is not None:
            qry = qry.filter(dataownercode=dataowner)
        return qry.values('pk', 'dataownercode', 'headsign', 'lineplanningnumber', 'publiclinenumber', 'json_lines')


class AdvancedLineSearchView(JSONListResponseMixin, ListView):
    model = Line
    render_object = 'object_list'

    def get_queryset(self):
        qry = super(AdvancedLineSearchView, self).get_queryset()
        needle = unicode(self.request.GET.get('search', '').replace('*', '%'))
        cached = cache.get('line-search_%s' % needle)
        if cached:
            return cached

        groups = needle.split(',')
        include = [self.add_filters(g) for g in groups if g != "" and g[0] != '!']
        exclude = [self.add_filters(g[1:]) for g in groups if g != "" and g[0] == '!']

        # TODO: Do something with exclude
        # .exclude(reduce(OR, exclude))
        qry = qry.filter(reduce(OR, include)).order_by('lineplanningnumber')

        line_list = qry.values('pk', 'dataownercode', 'headsign', 'lineplanningnumber', 'publiclinenumber', 'json_lines')
        for r in line_list:
            r['json_lines'] = json.loads(r['json_lines'])
        cache.set('line-search_%s' % needle, line_list)
        return line_list

    # TODO: Move this to model
    def add_filters(self, group):
        parts = group.split(':')
        q = Q(self.get_kwarg(parts[0], 'dataownercode'))

        if len(parts) > 1:
            q.add(self.get_kwarg(parts[1], 'lineplanningnumber'), Q.AND)

        return q

    # TODO: Move this to manager
    def get_kwarg(self, value, field):
        if "%" in value:
            if value[-1] == '%' and value[0] == '%':
                field += '__contains'
            elif value[-1] == '%':
                field += '__startswith'
            else:
                field += '__endswith'
            value = value.replace('%', '')
        return Q(**{field: value})

data/templates/data/line_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Lijnen zonder prijsdata{% endblock %}

{% block content %}
    <h2>Lijnen zonder prijsdata</h2>
    <strong>Aantal ontbrekende lijnen:</strong> {{ object_list|length }} <br/>
    <strong>Aantal geladen lijnen:</strong> {{ total }} <br/>
    <br />
    <div class="alert alert-warning">
        <i class="glyphicon glyphicon-alert"></i>&nbsp; Omdat treindata nog niet in deze database is geladen, wordt dit op dit moment niet getoond als ontbrekend.  Treinvervangend vervoer wordt wel getoond.
    </div>

    <div id="map" style="width: 100%; height: 400px;"></div>&nbsp;

    {% regroup object_list by get_dataownercode_display as dataownercode_list %}

    {% for dataowner in dataownercode_list %}
    <h4>{{ dataowner.grouper }}</h4>
    <table class="table table-striped">
        <tr>
            <th>Systeemlijnnummer</th>
            <th class="text-center">Lijnnummer</th>
            <th>Bestemming</th>
        </tr>
        {% for obj in dataowner.list %}
            <tr>
                <td>{{ obj.lineplanningnumber }}</td>
                <td class="text-center">{{ obj.publiclinenumber }}</td>
                <td>{{ obj.headsign }}</td>
            </tr>
        {% empty %}
            <tr><td colspan="3" class="text-center">Geen lijnen zonder prijsdata gevonden</td></tr>
        {% endfor %}
    </table>
    {% endfor %}
{% endblock %}

{% block extra_css %}
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.20.1/mapbox-gl.css' rel='stylesheet' />
{% endblock %}

{% block extra_js %}
<script src='https://api.mapbox.com/mapbox-gl-js/v0.20.1/mapbox-gl.js'></script>
<script type="text/javascript">
    $(function() {
        mapboxgl.accessToken = 'pk.eyJ1Ijoiam9lbGhhYXNub290IiwiYSI6ImNpcHZrdGpwZjAwNWtod2tzN3hpazBxdWoifQ.XTeKb4bh230TknKWTQsK8A';
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v9',
            center: [5.101711, 52.087901],
            zoom: 7,
            scrollZoom: true
        });
        var line_source, line_layer;
        map.on('load', function() {
            line_source = new mapboxgl.GeoJSONSource({
                "data": {
                    "type": "FeatureCollection",
                    "features": []
                }
            });
            map.addSource("lines", line_source);
            line_layer = map.addLayer({
                "id": "lines",
                "type": "line",
                "source": "lines",
                "layout": {
                    "line-join": "round",
                    "line-cap": "round"
                },
                "paint": {
                    "line-color": "#e74c3c",
                    "line-width": 1
                }
            });
            var popup = new mapboxgl.Popup({
                closeButton: false,
                closeOnClick: false
            });
            map.on('mousemove', function(e) {
                var features = map.queryRenderedFeatures(e.point, { layers: ['lines'] });
                // Change the cursor style as a UI indicator.
                map.getCanvas().style.cursor = (features.length) ? 'pointer' : '';

                if (!features.length) {
                    popup.remove();
                    return;
                }

                var feature = features[0];

                var html = "Lijn "+feature.properties.publiclinenumber+" ("+feature.properties.lineplanningnumber+")";
                popup.setLngLat(map.unproject(e.point))
                        .setHTML(html)
                        .addTo(map);
            });
            loadData(line_source);
        });
    })
    function loadData(line_source) {
        $.ajax("/data/lines/missing_prices.json", {
            success: function (data, status, xhr) {
                var features = []
                $.each(data.object_list, function(index, value) {
                    $.each(value.json_lines.features, function(i, v) {
                        features.push(v);
                    })
                });
                if (line_source) {
                    line_source.setData({
                        "type": "FeatureCollection",
                        "features": features
                    })
                }
            }
        });

    }
</script>
{% endblock %}