ovabo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from app.views import ListProductView, CreateProductView, UpdateProductView, ListLineView, UpdateLineView, \
    CreateLineView, ListCalendarView, UpdateCalendarView, CreateCalendarView, CreateAgeGroupView, UpdateAgeGroupView, ListAgeGroupView, \
    CloneLineView, CloneAgeGroupView, CloneCalendarView, CloneProductView, CreateSellerView, UpdateSellerView, \
    ListSellerView
from data.views import LineSearchView, AdvancedLineSearchView, MissingPriceDataReport, MissingPriceDataLinesView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^(/)?$', TemplateView.as_view(template_name="app/welcome.html")),

    url(r'^products/add', CreateProductView.as_view(), name="product_add"),
    url(r'^products/(?P<pk>\w+)/edit(/)?', UpdateProductView.as_view(), name="product_edit"),
    url(r'^products/(?P<pk>\w+)/clone(/)?', CloneProductView.as_view(), name="product_clone"),
    url(r'^products(/)?', ListProductView.as_view(), name="product_list"),

    url(r'^lines/add', CreateLineView.as_view(), name="line_add"),
    url(r'^lines/(?P<pk>\w+)/edit(/)?', UpdateLineView.as_view(), name="line_edit"),
    url(r'^lines/(?P<pk>\w+)/clone(/)?', CloneLineView.as_view(), name="line_clone"),
    url(r'^lines(/)?', ListLineView.as_view(), name="line_list"),

    url(r'^calendar/add', CreateCalendarView.as_view(), name="calendar_add"),
    url(r'^calander/(?P<pk>\w+)/edit(/)?', UpdateCalendarView.as_view(), name="calendar_edit"),
    url(r'^calander/(?P<pk>\w+)/clone(/)?', CloneCalendarView.as_view(), name="calendar_clone"),
    url(r'^calendar(/)?', ListCalendarView.as_view(), name="calendar_list"),

    url(r'^age/add', CreateAgeGroupView.as_view(), name="agegroup_add"),
    url(r'^age/(?P<pk>\w+)/edit(/)?', UpdateAgeGroupView.as_view(), name="agegroup_edit"),
    url(r'^age/(?P<pk>\w+)/clone(/)?', CloneAgeGroupView.as_view(), name="agegroup_clone"),
    url(r'^age(/)?', ListAgeGroupView.as_view(), name="agegroup_list"),

    url(r'^seller/add', CreateSellerView.as_view(), name="seller_add"),
    url(r'^seller/(?P<pk>\w+)/edit(/)?', UpdateSellerView.as_view(), name="seller_edit"),
    url(r'^seller(/)?', ListSellerView.as_view(), name="seller_list"),

    url(r'^data/reports/missing_prices(/)?', MissingPriceDataReport.as_view(), name="data_report_missing-price"),
    url(r'^data/lines/missing_prices.json', MissingPriceDataLinesView.as_view(), name="data_lines_missing-price_json"),

    url(r'^data/lines/advanced(/)?', AdvancedLineSearchView.as_view(), name="data_search_adv_line"),
    url(r'^data/lines(/)?', LineSearchView.as_view(), name="data_search_line"),


]

admin.site.site_header = 'OVabo'

data/models.py
from __future__ import unicode_literals

from django.db import models

from django.utils.translation import ugettext_lazy as _
from django_enumfield import enum

from utils.enums import TransportMode, DATAOWNERCODE


class Line(models.Model):
    dataownercode = models.CharField(max_length=6, choices=DATAOWNERCODE)
    lineplanningnumber = models.CharField(max_length=25)
    publiclinenumber = models.CharField(max_length=25)
    headsign = models.CharField(max_length=100)
    transportmode = enum.EnumField(TransportMode)
    json_lines = models.TextField()

    ppt_id = models.CharField(max_length=20, blank=True, null=True)
    ppt_name = models.CharField(max_length=100, blank=True, null=True)

    entrance = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Opstaptarief", blank=True, null=True)
    rounding = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Afrondniveau", blank=True, null=True)
    maximum = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Maximum eenheden", blank=True, null=True)
    average_km_rate = models.DecimalField(max_digits=8, decimal_places=5, verbose_name="Gemiddeld tarief", blank=True, null=True)

    class Meta:
        verbose_name = _("Lijn")
        verbose_name_plural = _("Lijninformatie")
        unique_together = ('dataownercode', 'lineplanningnumber')

    def __unicode__(self):
        return "%s - %s" % (self.dataownercode, self.headsign)

app/templates/app/agegroup_form.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}

{% block title %}{% if object.pk %}Specificeer leeftijdsgroep{% else %}Leeftijdsgroep toevoegen{% endif %}{% endblock %}

{% block content %}
    <h2>{% if object.pk %}Specificeer leeftijdsgroep{% else %}Leeftijdsgroep toevoegen{% endif %}</h2>

    <form class="form-horizontal"
          {% if object.pk %} action="{% url 'agegroup_edit' object.pk %}"{% else %} action="{% url 'agegroup_add' %}"{% endif %}
          method="post">
        {% crispy form form.helper %}

        {% if object.id %}
            <h4>Leeftijden</h4>
            {{ ages.management_form }}
            {% for item_form in ages %}
                <div class="inline">
                    {% crispy item_form item_form.helper %}
                </div>
            {% endfor %}
            <button type="button" class="btn btn-success btn-xs" data-action="add-formset"><i class="glyphicon glyphicon-plus"></i>&nbsp;{% trans "Patroon toevoegen" %}</button>
            <div class="empty-form inline">
                {% crispy ages.empty_form ages.empty_form.helper %}
            </div>
        {% endif %}

        <input type="submit" value="Opslaan" class="btn btn-primary pull-right" />
        <br/>
        <br/>
        <br/>

    </form>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'jquery.django-formset.js' %}"></script>
    <script type="text/javascript">
        $(function(){
            {% if object.id %}
                var formset = $('form').children('div.inline').djangoFormset({
                    'deleteButtonText' : "{% trans "Delete" %}"
                });
                $('form').on('click', '[data-action=add-formset]', function(event) {
                    var newForm = formset.addForm();
                });
            {% endif %}
        });
    </script>
{% endblock %}

app/templates/app/agegroup_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Leeftijdsgroepen{% endblock %}

{% block content %}
    <h2>Leeftijdsgroepen
        <a href="{% url "agegroup_add" %}" class="btn btn-success pull-right"><i class="glyphicon glyphicon-plus"></i> Nieuw</a>
    </h2>
    <table class="table table-striped">
        <tr>
            <th>Naam</th>
            <th class="text-center col-md-3">Leeftijdsreeksen</th>
            <th class="text-center">Acties</th>
        </tr>
        {% for obj in object_list %}
            <tr>
                <td><em>{{ obj.description }}</em></td>
                <td class="text-center">{{ obj.age_set.count }}</td>
                <td>
                    <a href="{% url 'agegroup_edit' obj.pk %}" class="btn btn-primary btn-xs pull-right"><i class="glyphicon glyphicon-pencil"></i>&nbsp;Bewerk</a>
                    <form action="{% url 'agegroup_clone' obj.id %}" method="post" >
                        {% csrf_token %}
                        <button class="btn btn-warning btn-xs pull-right" style="margin-right: 10px">
                            <span class="glyphicon glyphicon-repeat"></span> {% trans "Kopieer" %}
                        </button>
                    </form>
                </td>
            </tr>
        {% empty %}
            <tr><td colspan="3" class="text-center">Geen leeftijdsgroepen gevonden</td></tr>
        {% endfor %}
    </table>
{% endblock %}

app/templates/app/linegroup_form.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}

{% block title %}{% if object.pk %}Specificeer lijnen{% else %}Lijnen toevoegen{% endif %}{% endblock %}

{% block content %}
    <h2>{% if object.pk %}Specificeer lijnen{% else %}Lijnen toevoegen{% endif %}</h2>

    <form class="form-horizontal"
          {% if object.pk %} action="{% url 'line_edit' object.pk %}"{% else %} action="{% url 'line_add' %}"{% endif %}
          method="post">
        {% crispy form form.helper %}

        {% if object.id %}
            {% if object.source != 10 %}<input type="submit" value="Opslaan" class="btn btn-primary pull-right" /> <br />{% endif %}
            <div>
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation"><a href="#standard" role="tab" data-toggle="tab">Standaard</a></li>
                    <li role="presentation" class="active"><a href="#advanced" role="tab" data-toggle="tab">Geavanceerd</a></li>
                </ul>

                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane" id="standard">
                        <br />
                        <div class="alert alert-info">Hier kan je binnenkort lijnen kiezen op basis van een eindbestemming of lijnnummer.</div>
                    </div>
                    <div role="tabpanel" class="tab-pane active" id="advanced">
                        <br />
                        <div class="alert alert-info">Doormiddel van een of meer patronen kan je hier meerdere lijnen tegelijk kiezen. Bekijk rechts welke lijnen je hebt geselecteerd.
                            Formaat voor het patroon is <code>vervoerdercode:lijnsysteemnummer</code>. Gebruik sterretjes (<code>*</code>) om aan te geven of patroon moet beginnen of eindigen met de zoekterm.
                            Bijvoorbeeld <code>CXX:F*</code> of <code>ARR:*16</code>. Bekijk hier <a href="#codes" data-toggle="modal" data-target="#codes">de vervoerdercodes</a>.</div>
                        {{ lines.management_form }}
                        <div class="row">
                            <div class="col-md-4" id="line_forms">
                                {% for item_form in lines %}
                                    <div class="inline">
                                        {% crispy item_form item_form.helper %}
                                    </div>
                                {% endfor %}
                                <button type="button" class="btn btn-success btn-xs" data-action="add-formset"><i class="glyphicon glyphicon-plus"></i>&nbsp;{% trans "Patroon toevoegen" %}</button>
                                <a href="#codes" class="pull-right" data-toggle="modal" data-target="#codes">Bekijk vervoerdercodes</a>
                                <div class="empty-form inline">
                                    {% crispy lines.empty_form lines.empty_form.helper %}
                                </div>
                            </div>
                            <div class="col-md-8" >
                                <ul id="lines_tabs" class="nav nav-tabs navbar-right" role="tablist">
                                    <li role="presentation"><a href="#tab_map" role="tab" data-toggle="tab">Kaart</a></li>
                                    <li role="presentation"><a href="#tab_list" role="tab" data-toggle="tab">Lijst</a></li>
                                </ul>
                                <div class="clearfix"></div>

                                <div class="tab-content">
                                    <div role="tabpanel" class="tab-pane" id="tab_map">
                                        <div id="map" style="width: 100%; height: 400px;"></div>&nbsp;
                                        <div class="alert alert-warning">
                                            Tijdelijk worden uitgesloten lijnen nog wel getoond op de kaart - deze feature wordt binnenkort toegevoegd.
                                        </div>
                                    </div>
                                    <div role="tabpanel" class="tab-pane" id="tab_list">
                                        <table class="table table-bordered table-condensed table-striped">
                                            <tr>
                                                <th>Lijnnummer</th>
                                                <th>Bestemming</th>
                                            </tr>
                                            <tbody id="line_list">
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>

            </div>

            <div class="modal fade" id="codes" tabindex="-1" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Vervoerderscodes</h4>
                        </div>
                        <div class="modal-body">
                            <p>Gebruik de volgende vervoerdercodes:</p>
                            <table class="table table-bordered">
                                <tr>
                                    <th>Code</th><th>Omschrijving</th>
                                </tr>
                                {% for code in dataownercode %}
                                <tr>
                                    <td>{{ code.0 }}</td><td>{{ code.1 }}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

        {% if object.source != 10 %}<input type="submit" value="Opslaan" class="btn btn-primary pull-right" />{% endif %}
        <br/>
        <br/>
        <br/>

    </form>
{% endblock %}

{% block extra_css %}
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.20.1/mapbox-gl.css' rel='stylesheet' />
{% endblock %}

{% block extra_js %}
    <script src="{% static 'jquery.django-formset.js' %}"></script>
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.20.1/mapbox-gl.js'></script>
    <script type="text/javascript">
        $(function(){
            {% if object.id %}
                var formset = $('#line_forms').children('div.inline').djangoFormset({
                    'deleteButtonText' : "{% trans "Verwijder" %}"
                });
                $('form').on('click', '[data-action=add-formset]', function(event) {
                    var newForm = formset.addForm();
                });
                $('.inline').on('click', "[data-action=delete-formset]", function(event) {
                    refreshMap(line_source);
                });
                $("#advanced").on('blur', "input[name$='-pattern']", function() {
                    refreshMap(line_source);
                });

                mapboxgl.accessToken = 'pk.eyJ1Ijoiam9lbGhhYXNub290IiwiYSI6ImNpcHZrdGpwZjAwNWtod2tzN3hpazBxdWoifQ.XTeKb4bh230TknKWTQsK8A';
                var map = new mapboxgl.Map({
                    container: 'map',
                    style: 'mapbox://styles/mapbox/streets-v9',
                    center: [5.101711, 52.087901],
                    zoom: 7,
                    scrollZoom: true
                });
                var line_source, line_layer;
                map.on('load', function() {
                    line_source = new mapboxgl.GeoJSONSource({
                                "data": {
                                    "type": "FeatureCollection",
                                    "features": []
                                }
                            });
                    map.addSource("lines", line_source);
                    line_layer = map.addLayer({
                        "id": "lines",
                        "type": "line",
                        "source": "lines",
                        "layout": {
                            "line-join": "round",
                            "line-cap": "round"
                        },
                        "paint": {
                            "line-color": "#9c27b0",
                            "line-width": 1
                        }
                    });
                    refreshMap(line_source); /* Grab existing records */
                });
                // Create a popup, but don't add it to the map yet.
                var popup = new mapboxgl.Popup({
                    closeButton: false,
                    closeOnClick: false
                });

                map.on('mousemove', function(e) {
                    var features = map.queryRenderedFeatures(e.point, { layers: ['lines'] });
                    // Change the cursor style as a UI indicator.
                    map.getCanvas().style.cursor = (features.length) ? 'pointer' : '';

                    if (!features.length) {
                        popup.remove();
                        return;
                    }

                    var feature = features[0];

                    var html = "Lijn "+feature.properties.publiclinenumber+" ("+feature.properties.lineplanningnumber+")";
                    popup.setLngLat(map.unproject(e.point))
                            .setHTML(html)
                            .addTo(map);
                });

                $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                    console.log("Got tab shown");
                    map.resize();
                });
                $('#lines_tabs a:first').tab('show');
            {% endif %}
        });
        function refreshMap(line_source) {
            var lines = "";
            $("div.inline").each(function(i, v) {
                var value = $(v).find("input[name$='-pattern']").val()
                if (lines != "") {
                    lines += ","
                }
                if ($(v).find("select[name$='-type']").val() == 2) {
                    value = "!" + value;
                }
                if (value != "") {
                    lines += value;
                }
            });
            $.ajax("/data/lines/advanced?search="+lines, {
                success: function (data, status, xhr) {
                    var features = []
                    /* TODO: We should think about doing this serverside */
                    $.each(data.object_list, function(index, value) {
                        $.each(value.json_lines.features, function(i, v) {
                            features.push(v);
                        })
                    });
                    if (line_source) {
                        line_source.setData({
                            "type": "FeatureCollection",
                            "features": features
                        })
                    }
                }
            });
        }
    </script>
{% endblock %}

app/templates/app/linegroup_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Lijnen{% endblock %}

{% block content %}
    <h2>Lijnen
        <a href="{% url "line_add" %}" class="btn btn-success pull-right"><i class="glyphicon glyphicon-plus"></i> Nieuw</a>
    </h2>
    <table class="table table-striped">
        <tr>
            <th>Naam</th>
            <th class="text-center col-md-2">Lijnen/patronen</th>
            <th class="text-center">Acties</th>
        </tr>
        {% for obj in object_list %}
            <tr>
                <td class="col-md-6">
                    <em>{% if obj.source == 10 %}<i class="glyphicon glyphicon-import"></i>&nbsp;{% endif %}
                        {{ obj.description }}</em>
                    <span class="pull-right">
                        {% if obj.incomplete %}<i title="Nog niet compleet" class="glyphicon glyphicon-exclamation-sign text-warning"></i>{% endif %}
                        {% if obj.validated %}<i title="Gevalideerd" class="glyphicon glyphicon-check text-success"></i>{% endif %}
                    </span>
                </td>
                <td class="text-center">{{ obj.line_set.count }}</td>
                <td class="col-md-4">
                    {% if obj.source != 10 %}
                        <a href="{% url 'line_edit' obj.pk %}" class="btn btn-primary btn-xs pull-right"><i class="glyphicon glyphicon-pencil"></i>&nbsp;Bewerk</a>
                    {% else %}
                        <a href="{% url 'line_edit' obj.pk %}" class="btn btn-succes btn-xs pull-right"><i class="glyphicon glyphicon-zoom-in"></i>&nbsp;Bekijk</a>
                    {% endif %}
                    <form action="{% url 'line_clone' obj.id %}" method="post" >
                        {% csrf_token %}
                        <button class="btn btn-warning btn-xs pull-right" style="margin-right: 10px">
                            <span class="glyphicon glyphicon-repeat"></span> {% trans "Kopieer" %}
                        </button>
                    </form>

                </td>
            </tr>
        {% empty %}
            <tr><td colspan="3" class="text-center">Geen lijnen gevonden</td></tr>
        {% endfor %}
    </table>
{% endblock %}

app/templates/app/product_list.html
{% extends "base.html" %}

{% block title %}Product{% endblock %}

{% block content %}
    <h2>Product
        <a href="{% url "product_add" %}" class="btn btn-success pull-right"><i class="glyphicon glyphicon-plus"></i> Nieuw</a>
    </h2>
    <table class="table table-striped">
        <tr>
            <th>Naam</th>
            <th class="text-center">Prijs</th>
            <th class="text-center">Kortingen</th>
            <th class="text-right">Acties</th>
        </tr>
        {% for abo in object_list %}
            <tr>
                <td><em>{{ abo.name }}</em>
                    <span class="pull-right">
                        {% if abo.incomplete %}<i title="Nog niet compleet" class="glyphicon glyphicon-exclamation-sign text-warning"></i>{% endif %}
                        {% if abo.validated %}<i title="Gevalideerd" class="glyphicon glyphicon-check text-success"></i>{% endif %}
                    </span>
                </td>
                <td class="text-center"><small>
                    {% for price in abo.prices.all %}
                        {{ price.get_duration_display }}: &euro; {{ price.price }}<br/>
                    {% endfor %}
                    </small>
                </td>
                <td class="text-center">{{ abo.productreduction_set.count }}</td>
                <td>
                    <a href="{% url 'product_edit' abo.pk %}" class="btn btn-primary btn-xs pull-right"><i class="glyphicon glyphicon-pencil"></i>&nbsp;Bewerk</a>
                    <form action="{% url 'product_clone' abo.id %}" method="post" >
                        {% csrf_token %}
                        <button class="btn btn-warning btn-xs pull-right" style="margin-right: 10px">
                            <span class="glyphicon glyphicon-repeat"></span> Kopieer
                        </button>
                    </form>
                </td>
            </tr>
        {% empty %}
            <tr><td colspan="5" class="text-center">Geen producten gevonden</td></tr>
        {% endfor %}
    </table>
{% endblock %}

app/templates/app/seller_form.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}

{% block title %}{% if object.pk %}Verkooppartij bewerken{% else %}Verkooppartij toevoegen{% endif %}{% endblock %}

{% block content %}
    <h2>{% if object.pk %}Verkooppartij bewerken{% else %}Verkooppartij toevoegen{% endif %}</h2>

    <form class="form-horizontal"
          {% if object.pk %} action="{% url 'seller_edit' object.pk %}"{% else %} action="{% url 'seller_add' %}"{% endif %}
          method="post">
        {% crispy form form.helper %}

        <input type="submit" value="Opslaan" class="btn btn-primary pull-right" />
        <br/>
        <br/>
        <br/>

    </form>
{% endblock %}

app/templates/app/seller_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Verkooppartijen{% endblock %}

{% block content %}
    <h2>Verkooppartijen
        <a href="{% url "seller_add" %}" class="btn btn-success pull-right"><i class="glyphicon glyphicon-plus"></i> Nieuw</a>
    </h2>
    <table class="table table-striped">
        <tr>
            <th>Naam</th>
            <th class="text-center col-md-3">Telefoon</th>
            <th class="text-center">Acties</th>
        </tr>
        {% for obj in object_list %}
            <tr>
                <td><em>{{ obj.name }}</em></td>
                <td class="text-center">{{ obj.phone }}<br />{{ obj.url }}</td>
                <td>
                    <a href="{% url 'seller_edit' obj.pk %}" class="btn btn-primary btn-xs pull-right"><i class="glyphicon glyphicon-pencil"></i>&nbsp;Bewerk</a>
                </td>
            </tr>
        {% empty %}
            <tr><td colspan="3" class="text-center">Geen verkooppartijen gevonden</td></tr>
        {% endfor %}
    </table>
{% endblock %}

app/templates/app/temporalavailability_form.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}

{% block title %}{% if not object.id %}Kalender toevoegen{% else %}Specificeer kalender{% endif %}{% endblock %}

{% block content %}
    {% if not object.id %} {% comment %} Add {% endcomment %}
        <h2>Kalender toevoegen</h2>
        <form class="form-horizontal" action="{% url 'calendar_add' %}" method="post">
            {% crispy form form.helper %}
            <input type="submit" value="Toevoegen" class="btn btn-primary pull-right" />
        </form>
    {% else %}
        <h2>Specificeer kalender</h2>
        <form class="form-horizontal" action="{% url 'calendar_edit' object.pk %}" method="post">
            {% crispy form form.helper %}
            <input type="submit" value="Opslaan" class="btn btn-primary pull-right" />

            {{ weekdays.management_form }}
            <br />
            <h5>Periodes</h5>
            {% for item_form in weekdays %}
                <div class="inline">
                    {% crispy item_form item_form.helper %}
                </div>
            {% endfor %}
            <button type="button" class="btn btn-success btn-xs" data-action="add-formset"><i class="glyphicon glyphicon-plus"></i>&nbsp;{% trans "Korting toevoegen" %}</button>
            <div class="empty-form inline">
                {% crispy weekdays.empty_form weekdays.empty_form.helper %}
            </div>

        </form>
    {% endif %}
{% endblock %}

{% block extra_js %}
    <script src="{% static 'jquery.django-formset.js' %}"></script>
    <script type="text/javascript">
        $(function(){
            {% if object.id %}
            var formset = $('form').children('div.inline').djangoFormset({
                'deleteButtonText' : "{% trans "Delete" %}"
            });
            $('form').on('click', '[data-action=add-formset]', function(event) {
                var newForm = formset.addForm();
            });
            {% endif %}
        });
    </script>
{% endblock %}

app/templates/app/temporalavailability_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Kalenders{% endblock %}

{% block content %}
    <h2>Kalenders
        <a href="{% url "calendar_add" %}" class="btn btn-success pull-right"><i class="glyphicon glyphicon-plus"></i> Nieuw</a>
    </h2>
    <table class="table table-striped">
        <tr>
            <th>Naam</th>
            <th class="text-center col-md-2">Periodes</th>
            <th class="text-center">Acties</th>
        </tr>
        {% for obj in object_list %}
            <tr>
                <td><em>{{ obj.description }}</em></td>
                <td class="text-center">{{ obj.weekdays_set.count }}</td>
                <td>
                    <a href="{% url 'calendar_edit' obj.pk %}" class="btn btn-primary btn-xs pull-right"><i class="glyphicon glyphicon-pencil"></i>&nbsp;Bewerk</a>
                    <form action="{% url 'calendar_clone' obj.id %}" method="post" >
                        {% csrf_token %}
                        <button class="btn btn-warning btn-xs pull-right" style="margin-right: 10px">
                            <span class="glyphicon glyphicon-repeat"></span> {% trans "Kopieer" %}
                        </button>
                    </form>
                </td>
            </tr>
        {% empty %}
            <tr><td colspan="3" class="text-center">Geen kalenders gevonden</td></tr>
        {% endfor %}
    </table>
{% endblock %}

app/templates/app/welcome.html
{% extends "base.html" %}
{% load static i18n crispy_forms_tags %}

{% block title %}Welkom{% endblock %}

{% block content %}
    <h1>Welkom</h1>
    <div class="alert alert-success">Kies bovenin het scherm de lijst met producten in verder te gaan.</div>
    <br /><br />
    In overeenstemming met de licentie voor deze broncode van deze applicatie is de broncode <a href="https://github.com/bliksemlabs/ovabo">hier beschikbaar</a>.
{% endblock %}